---
apiVersion: v1
kind: Secret
metadata:
  name: appium-secrets
  namespace: appium
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appium
  namespace: appium
spec:
  selector:
    matchLabels:
      app: appium
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: appium
    spec:
      containers:
        - name: appium
          image: public.ecr.aws/g7c8o4c7/appium:latest
          ports:
            - name: appium
              containerPort: 4723
          env:
            - name: REMOTE_ADB
              value: "true"
        - name: ssh
          image: public.ecr.aws/g7c8o4c7/awsssh:0.0.4
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: appium-secrets
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: appium-secrets
            - name: AWS_REGION
              value: "ap-northeast-1"
          volumeMounts:
            - name: genymotion-pem
              mountPath: /root/ssh
              readOnly: true
          ports:
            - name: http
              containerPort: 5555
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 128Mi
              cpu: "0.2"
      volumes:
        - name: genymotion-pem
          secret:
            secretName: genymotion-pem
            items:
              - key: cert.pem
                path: cert.pem