apiVersion: v1
kind: Namespace
metadata:
  name: appium
---
apiVersion: v1
kind: Secret
metadata:
  name: genymotion-pem
  namespace: appium
type: Opaque
data:
  android.pem:
  config: 
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: appium
  labels:
    app: ssh
spec:
  ports:
    - port: 5555
      name: ssh
  selector:
    app: ssh
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: appium
  namespace: appium
  labels:
    app: appium
spec:
  ports:
    - port: 4723
      name: appium
  selector:
    app: appium
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  namespace: appium
  labels:
    app: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
        - name: ssh
          image: cagataygurturk/docker-ssh-tunnel:0.0.3
          command: ["/bin/sh"]
          args: ["-c", "rm -rf /root/.ssh && mkdir /root/.ssh && cp -L /root/ssh/* /root/.ssh/ && ls -la /root/.ssh && chmod -R 600 /root/.ssh/* && ssh $SSH_DEBUG -o StrictHostKeyChecking=no -N $TUNNEL_HOST -L *:$LOCAL_PORT:$REMOTE_HOST:$REMOTE_PORT && while true; do sleep 30; done;"]
          env:
            - name: TUNNEL_HOST
              value: "10.100.200.100"
            - name: REMOTE_HOST
              value: "localhost"
            - name: LOCAL_PORT
              value: "5555"
            - name: REMOTE_PORT
              value: "5555"
          volumeMounts:
            - name: genymotion-pem
              mountPath: /root/ssh
              readOnly: true
          ports:
            - name: http
              containerPort: 5555
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 512Mi
              cpu: "0.2"
      volumes:
        - name: genymotion-pem
          secret:
            secretName: genymotion-pem
            items:
            - key: android.pem
              path: android.pem
            - key: config
              path: config
---


