name: Development Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      make_appium:
        description: 'Build Appium container'
        type: boolean
        default: false
      make_ssh:
        description: 'Build SSH container'
        type: boolean
        default: false
      ssh_container_version:
        description: 'SSH container version tag'
        type: string
        default: 'latest'

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/g7c8o4c7
  APPIUM_IMAGE_NAME: appium
  SSH_IMAGE_NAME: awsssh

jobs:
  build:
    runs-on: ${{ vars.RUNNER_LABELS || 'ubuntu-latest' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: kubernetes
        driver-opts: |
          namespace=github-new
          replicas=1
          "rootless=true"
        platforms: linux/amd64

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR Public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Set image tag
      id: tag
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=${{ github.head_ref }}" >> $GITHUB_OUTPUT
        fi

    - name: Build Appium Docker image (no push)
      if: github.event.inputs.make_appium == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ env.ECR_REGISTRY }}/${{ env.APPIUM_IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
        build-args: |
          NEW_RELIC_MOBILE_KEY=${{ secrets.NEW_RELIC_MOBILE_KEY }}
        network: host

    - name: Build SSH Docker image (no push)
      if: github.event.inputs.make_ssh == 'true'
      uses: docker/build-push-action@v5
      with:
        context: ./deployment
        push: false
        tags: ${{ env.ECR_REGISTRY }}/${{ env.SSH_IMAGE_NAME }}:${{ github.event.inputs.ssh_container_version || 'latest' }}
        network: host